// 2.0/vue-vite/src/App.vue
<template>
  <div class="container">
    <h1>CueSync with Vue + Vite</h1>

    <video id="natGeoVideo" controls style="width: 100%; max-width: 500px; border-radius: 10px;">
      <source src="/assets/videos/natgeo.mp4" type="video/mp4" />
      Your browser does not support HTML video.
    </video>

    <cue-sync
            transcript-path="/assets/transcripts/natgeo.vtt, /assets/transcripts/natgeo_hindi.vtt"
            media="#natGeoVideo"
            style="height: 400px; max-width: 500px;"
    ></cue-sync>
  </div>
</template>

// 2.0/cuesync-angular/src/app/app.component.ts
import { Component } from '@angular/core';
import { RouterOutlet } from '@angular/router';
import { CUSTOM_ELEMENTS_SCHEMA } from '@angular/core';

@Component({
  selector: 'app-root',
  imports: [RouterOutlet],
  templateUrl: './app.component.html',
  styleUrl: './app.component.scss',
  schemas: [CUSTOM_ELEMENTS_SCHEMA]
})
export class AppComponent {
  title = 'cuesync-angular';
}

<h1>CueSync + Angular (Standalone)</h1>

<video id="natgeoVideo" controls style="width: 100%; max-width: 500px; border-radius: 10px;">
  <source src="/assets/videos/natgeo.mp4" type="video/mp4" />
</video>

<cue-sync
        transcript-path="/assets/transcripts/natgeo.vtt, /assets/transcripts/natgeo_hindi.vtt"
        media="#natgeoVideo"
        style="height: 400px; max-width: 500px;"
></cue-sync>
