// 2.0/react-vite/src/App.jsx
import '@cuesync/cuesync'
import './App.css'

function App() {

  return (
    <div>
      <h1>CueSync React + Vite</h1>

      <video id="natGeoVideo" controls style={{ width: '100%', maxWidth: '500px',  borderRadius: '10px' }}>
        <source src="/assets/videos/natgeo.mp4" type="video/mp4" />
        Your browser does not support HTML video.
      </video>

      <cue-sync
        transcript-path="/assets/transcripts/natgeo.vtt, /assets/transcripts/natgeo_hindi.vtt"
        media="#natGeoVideo"
        style={{ height: '400px', maxWidth: '500px' }}
      ></cue-sync>
    </div>
  )
}

export default App

// 2.0/vue-vite/src/App.vue
<template>
  <div class="container">
    <h1>CueSync with Vue + Vite</h1>

    <video id="natGeoVideo" controls style="width: 100%; max-width: 500px; border-radius: 10px;">
      <source src="/assets/videos/natgeo.mp4" type="video/mp4" />
      Your browser does not support HTML video.
    </video>

    <cue-sync
            transcript-path="/assets/transcripts/natgeo.vtt, /assets/transcripts/natgeo_hindi.vtt"
            media="#natGeoVideo"
            style="height: 400px; max-width: 500px;"
    ></cue-sync>
  </div>
</template>
